### ISSUE TITLE
TAGML Description of rich text is outdated/wrong.

### ISSUE THREAD

**Issue by rhdekker** [HuygensING/TAG#1]
It says:
mixed content: |mixed [b>content<b]| (bracketed by |)

Mixed content is an xml term.
Should be:
rich text content: |>rich text [b>content<b]<| (bracketed by |> <|)

**Comment by brambg** [comment]
"mixed content"  has been replaced  with "rich text"

**Comment by rhdekker** [comment]
@brambg  Thanks for the update, but the description is still not completely correct: For rich text it says now: | rich text | but it should be |> rich text <| bracketed by |> and <|

**Comment by brambg** [comment]
I missed that. Fixed now.
